import React, { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

export type Language = 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation keys
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.warning': 'Warning',
    'common.search': 'Search',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.tickets': 'Tickets',
    'nav.machines': 'Machines',
    'nav.reports': 'Reports',
    'nav.users': 'Users',
    'nav.settings': 'Settings',
    
    // Authentication
    'auth.login': 'Login',
    'auth.logout': 'Logout',
    'auth.register': 'Register',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.email': 'Email',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.employeeID': 'Employee ID',
    'auth.department': 'Department',
    'auth.shift': 'Shift',
    'auth.currentPassword': 'Current Password',
    'auth.newPassword': 'New Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.changePassword': 'Change Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.rememberMe': 'Remember Me',
    'auth.loginSuccess': 'Login successful',
    'auth.logoutSuccess': 'Logout successful',
    'auth.registrationSuccess': 'Registration successful',
    'auth.passwordChangeSuccess': 'Password changed successfully',
    
    // User roles
    'role.l1_operator': 'L1 Operator',
    'role.l2_engineer': 'L2 Engineer',
    'role.l3_manager': 'L3 Manager',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    
    // Profile
    'profile.title': 'User Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.workInfo': 'Work Information',
    'profile.lastLogin': 'Last Login',
    'profile.memberSince': 'Member Since',
    'profile.profileInformation': 'Profile Information',
    'profile.changeProfilePicture': 'Change Profile Picture',
    'profile.upload': 'Upload',
    'profile.chooseFile': 'Choose File',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.jobTitle': 'Title',
    'profile.department': 'Department',
    'profile.group': 'Group',
    'profile.personCode': 'Person Code',
    'profile.saveChanges': 'Save Changes',
    'profile.profileUpdated': 'Profile updated',
    'profile.failedToUpdateProfile': 'Failed to update profile',
    'profile.avatarUpdated': 'Avatar updated',
    'profile.failedToUploadAvatar': 'Failed to upload avatar',
    'profile.lineNotifications': 'LINE Notifications',
    'profile.lineUserId': 'LINE User ID (for notifications)',
    'profile.enterLineId': 'Enter your LineID',
    'profile.sendTestLineNotification': 'Send Test LINE Notification',
    'profile.ensureLineIdSet': 'Ensure your LineID is set above.',
    'profile.testNotificationSent': 'Test notification sent to your LINE.',
    'profile.failedToSendTestNotification': 'Failed to send test notification',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.passwordChanged': 'Password changed',
    'profile.failedToChangePassword': 'Failed to change password',
    'profile.lineHelpTitle': 'How to get your LINE User ID',
    'profile.lineHelpDescription': 'Follow these steps to get your LINE User ID for notifications:',
    'profile.step1Title': 'Add our LINE Official Account',
    'profile.step1Description': 'Scan the QR code below or click the link to add our LINE account as a friend.',
    'profile.addLineFriend': 'Add LINE Friend',
    'profile.step2Title': 'Send "Line ID" message',
    'profile.step2Description': 'Open the chat with our LINE account and send the message:',
    'profile.step3Title': 'Copy your User ID',
    'profile.step3Description': 'Copy the returned User ID and paste it in the field above.',
    'profile.gotIt': 'Got it!',
    'profile.cropAvatar': 'Crop Avatar',
    'profile.zoom': 'Zoom',
    'profile.cancel': 'Cancel',
    'profile.apply': 'Apply',
    'profile.failedToCropImage': 'Failed to crop image',
    
    // Settings
    'settings.title': 'Settings',
    'settings.appearance': 'Appearance',
    'settings.language': 'Language',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    
    // Theme
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.auto': 'Auto',
    
    // Language
    'language.english': 'English',
    'language.thai': 'ไทย',
    
    // Errors
    'error.invalidCredentials': 'Invalid username or password',
    'error.userNotFound': 'User not found',
    'error.unauthorized': 'Unauthorized access',
    'error.forbidden': 'Access forbidden',
    'error.notFound': 'Page not found',
    'error.serverError': 'Internal server error',
    'error.networkError': 'Network error',
    'error.validationError': 'Validation error',
    
    // Validation
    'validation.required': 'This field is required',
    'validation.email': 'Please enter a valid email address',
    'validation.passwordLength': 'Password must be at least 6 characters long',
    'validation.passwordMatch': 'Passwords do not match',
    'validation.usernameLength': 'Username must be at least 3 characters long',
    
    // Homepage specific
    'homepage.welcome': 'Welcome back',
    'homepage.quickActions': 'Quick Actions',
    'homepage.pendingTickets': 'Pending Tickets',
    'homepage.personal': 'Personal',
    'homepage.team': 'Team',
    'homepage.createTicket': 'Create Ticket',
    'homepage.viewTickets': 'View Tickets',
    'homepage.reportNewIssue': 'Report a new issue or request',
    'homepage.checkTicketStatus': 'Check your ticket status',
    'homepage.loadingPendingTickets': 'Loading pending tickets...',
    'homepage.errorLoadingTickets': 'Error loading tickets',
    'homepage.noPendingTickets': 'No pending tickets',
    'homepage.allTicketsUpToDate': 'All your tickets are up to date!',
    'homepage.youCreatedThisTicket': 'You created this ticket',
    'homepage.requiresYourApproval': 'Requires your approval',
    'homepage.viewOnly': 'View only',
    'homepage.myCompleteCasesPerPeriod': 'My Complete Cases Per Period',
    'homepage.myReportCasePerPeriod': 'My Report Case Per Period',
    'homepage.setupKPI': 'Setup KPI',
    'homepage.errorLoadingChartData': 'Error loading chart data',
    'homepage.noCompletedTicketData': 'No completed ticket data available',
    'homepage.completeSomeTickets': 'Complete some tickets to see your performance!',
    'homepage.noTicketDataAvailable': 'No ticket data available',
    'homepage.startCreatingTickets': 'Start creating tickets to see your performance!',
    'homepage.asReporter': 'As Reporter (How I Help by Reporting)',
    'homepage.asActionPerson': 'As Action Person (How I Help by Fixing)',
    'homepage.errorLoadingKPIData': 'Error loading KPI data',
    'homepage.loadingPersonalMetrics': 'Loading personal metrics...',
    'homepage.noKPIDataAvailable': 'No KPI data available',
    'homepage.myReportsCreated': 'My Reports Created',
    'homepage.downtimeAvoidedByMyReports': 'Downtime Avoided by My Reports',
    'homepage.costAvoidedByMyReports': 'Cost Avoided by My Reports',
    'homepage.casesIFixed': 'Cases I Fixed',
    'homepage.downtimeIFixed': 'Downtime I Fixed',
    'homepage.costIFixed': 'Cost I Fixed',
    'homepage.noChange': 'No change',
    'homepage.teamPerformance': 'Team Performance',
    'homepage.teamPerformanceComingSoon': 'Team performance metrics coming soon...',
    'homepage.filters': 'Filters',
    'homepage.range': 'Range',
    'homepage.currentSelection': 'Current Selection',
    'homepage.thisYear': 'This Year',
    'homepage.lastYear': 'Last Year',
    'homepage.thisPeriod': 'This Period',
    'homepage.completedTickets': 'Completed Tickets',
    'homepage.target': 'Target',
    'homepage.myTickets': 'My Tickets',
    'homepage.failedToFetchPendingTickets': 'Failed to fetch pending tickets',
    'homepage.failedToFetchPersonalTicketData': 'Failed to fetch personal ticket data',
    'homepage.failedToFetchPersonalCompletedTicketData': 'Failed to fetch personal completed ticket data',
    'homepage.failedToFetchPersonalKPIData': 'Failed to fetch personal KPI data',
    
    // Personal KPI Modal
    'personalKPI.title': 'Personal KPI Target Setup',
    'personalKPI.reportCases': 'Report Cases',
    'personalKPI.fixCases': 'Fix Cases',
    'personalKPI.error': 'Error',
    'personalKPI.success': 'Success',
    'personalKPI.validationError': 'Validation Error',
    'personalKPI.failedToFetchExistingTargets': 'Failed to fetch existing targets',
    'personalKPI.userInformationNotAvailable': 'User information not available',
    'personalKPI.failedToSavePersonalTargets': 'Failed to save personal targets',
    'personalKPI.user': 'User',
    'personalKPI.personNo': 'Person No',
    'personalKPI.year': 'Year',
    'personalKPI.unit': 'Unit',
    'personalKPI.case': 'Case',
    'personalKPI.thb': 'THB',
    'personalKPI.percent': 'Percent',
    'personalKPI.existingTargetsWarning': 'You already have targets set for {type} in {year}. Saving new values will replace the existing targets.',
    'personalKPI.periodValues': 'Period Values',
    'personalKPI.copyP1ToAll': 'Copy P1 to All',
    'personalKPI.resetForm': 'Reset Form',
    'personalKPI.cancel': 'Cancel',
    'personalKPI.saveTargets': 'Save Targets',
    'personalKPI.saving': 'Saving...',
    'personalKPI.fillAllPeriods': 'Please fill in values for all periods: {periods}',
    'personalKPI.targetsSavedSuccess': 'Personal targets saved successfully for {type} in {year}',
    'personalKPI.report': 'Report',
    'personalKPI.fix': 'Fix',
    'personalFilter.title': 'Personal Performance Filters',
    'personalFilter.timeRange': 'Time Range',
    'personalFilter.selectTimeRange': 'Select time range',
    'personalFilter.thisYear': 'This Year',
    'personalFilter.lastYear': 'Last Year',
    'personalFilter.thisPeriod': 'This Period',
    'personalFilter.selectPeriod': 'Select Period',
    'personalFilter.year': 'Year',
    'personalFilter.period': 'Period',
    'personalFilter.applyFilters': 'Apply Filters',
    
    // Common chart labels
    'chart.completedTickets': 'Completed Tickets',
    'chart.target': 'Target',
    'chart.myTickets': 'My Tickets',
    
    // Ticket Management
    'ticket.create': 'Create Ticket',
    'ticket.edit': 'Edit Ticket',
    'ticket.view': 'View Ticket',
    'ticket.title': 'Title',
    'ticket.description': 'Description',
    'ticket.status': 'Status',
    'ticket.priority': 'Priority',
    'ticket.severity': 'Severity',
    'ticket.pucode': 'PUCODE',
    'ticket.area': 'Area',
    'ticket.created': 'Created',
    'ticket.updated': 'Updated',
    'ticket.assignee': 'Assignee',
    'ticket.reporter': 'Reporter',
    'ticket.reportAbnormalFinding': 'Report Abnormal Finding',
    'ticket.briefDescription': 'Brief description of the abnormal finding',
    'ticket.detailedDescription': 'Detailed description of the abnormal finding, including symptoms and observations',
    'ticket.titleRequired': 'Title is required',
    'ticket.descriptionRequired': 'Description is required',
    'ticket.pucodeRequired': 'PUCODE is required',
    'ticket.machineName': 'Machine Name', // Added machine name
    'ticket.ticketCreatedSuccess': 'Ticket created successfully',
    'ticket.ticketUpdatedSuccess': 'Ticket updated successfully',
    'ticket.failedToCreateTicket': 'Failed to create ticket',
    'ticket.failedToUpdateTicket': 'Failed to update ticket',
    'ticket.failedToFetchTickets': 'Failed to fetch tickets',
    'ticket.noTicketsFound': 'No tickets found',
    'ticket.loadingTickets': 'Loading tickets...',
    'ticket.errorLoadingTickets': 'Error loading tickets',
    'ticket.searchTickets': 'Search tickets...',
    'ticket.filterByStatus': 'Filter by status',
    'ticket.filterByPriority': 'Filter by priority',
    'ticket.filterBySeverity': 'Filter by severity',
    'ticket.allStatuses': 'All Statuses',
    'ticket.allPriorities': 'All Priorities',
    'ticket.allSeverities': 'All Severities',
    'ticket.allAreas': 'All Areas',
    'ticket.open': 'Open',
    'ticket.assigned': 'Assigned',
    'ticket.inProgress': 'In Progress',
    'ticket.pending': 'Pending',
    'ticket.resolved': 'Resolved',
    'ticket.closed': 'Closed',
    'ticket.cancelled': 'Cancelled',
    'ticket.low': 'Low',
    'ticket.medium': 'Medium',
    'ticket.high': 'High',
    'ticket.critical': 'Critical',
    'ticket.normal': 'Normal',
    'ticket.urgent': 'Urgent',
    'ticket.costAvoidance': 'Cost Avoidance',
    'ticket.downtimeAvoidance': 'Downtime Avoidance (Hours)',
    'ticket.failureMode': 'Failure Mode',
    'ticket.attachments': 'Attachments',
    'ticket.addAttachment': 'Add Attachment',
    'ticket.removeAttachment': 'Remove Attachment',
    'ticket.comments': 'Comments',
    'ticket.addComment': 'Add Comment',
    'ticket.noComments': 'No comments yet',
    'ticket.history': 'History',
    'ticket.timeline': 'Timeline',
    'ticket.actions': 'Actions',
    'ticket.approve': 'Approve',
    'ticket.reject': 'Reject',
    'ticket.assign': 'Assign',
    'ticket.unassign': 'Unassign',
    'ticket.close': 'Close',
    'ticket.reopen': 'Reopen',
    'ticket.duplicate': 'Duplicate',
    'ticket.duplicateTicket': 'Duplicate Ticket',
    'ticket.originalTicket': 'Original Ticket',
    'ticket.relatedTickets': 'Related Tickets',
    'ticket.dependencies': 'Dependencies',
    'ticket.tags': 'Tags',
    'ticket.addTag': 'Add Tag',
    'ticket.removeTag': 'Remove Tag',
    'ticket.wizard': 'Ticket Creation Wizard',
    'ticket.wizardStep1': 'Step 1: Basic Information',
    'ticket.wizardStep2': 'Step 2: Details',
    'ticket.wizardStep3': 'Step 3: Review',
    'ticket.wizardNext': 'Next',
    'ticket.wizardPrevious': 'Previous',
    'ticket.wizardFinish': 'Finish',
    'ticket.wizardCancel': 'Cancel',
    'ticket.wizardBack': 'Back',
    'ticket.wizardReview': 'Review',
    'ticket.wizardConfirm': 'Confirm',
    'ticket.wizardSuccess': 'Ticket created successfully!',
    'ticket.wizardError': 'Error creating ticket',
    'ticket.wizardValidationError': 'Please fill in all required fields',
    'ticket.wizardSelectPlant': 'Select Plant',
    'ticket.wizardSelectArea': 'Select Area',
    'ticket.wizardSelectLine': 'Select Line',
    'ticket.wizardSelectMachine': 'Select Machine',
    'ticket.wizardSelectPUCODE': 'Select PUCODE',
    'ticket.wizardSelectFailureMode': 'Select Failure Mode',
    'ticket.wizardUploadImages': 'Upload Images',
    'ticket.wizardDragDropImages': 'Drag and drop images here, or click to select',
    'ticket.wizardImagePreview': 'Image Preview',
    'ticket.wizardRemoveImage': 'Remove Image',
    'ticket.wizardMaxImages': 'Maximum 5 images allowed',
    'ticket.wizardImageSize': 'Image size should be less than 5MB',
    'ticket.wizardImageFormat': 'Only JPG, PNG, GIF formats are allowed',
    'ticket.deleteConfirm': 'Are you sure you want to delete this ticket?',
    'ticket.ticketDeletedSuccess': 'Ticket deleted successfully',
    'ticket.failedToDeleteTicket': 'Failed to delete ticket',
    'ticket.warning': 'Warning',
    'ticket.fileSkipped': 'Some files were skipped. Only image files are supported.',
    'ticket.fileSizeExceeded': 'file(s) were skipped. Maximum file size is 10MB.',
    'ticket.searchMachines': 'Searching...',
    'ticket.failedToSearchMachines': 'Failed to search machines. Please try again.',
    'ticket.selectMachine': 'Please select a machine',
    'ticket.atLeastOneAttachment': 'At least one attachment is required',
    'ticket.selectedMachine': 'Selected Machine',
    'ticket.typeToSearch': 'Type at least 2 characters to search. Only 5-section PUCODEs (Plant-Area-Line-Machine-Number) are shown for abnormal findings.',
    'ticket.attachImages': 'Attach Images (Before)',
    'ticket.dragDropFiles': 'Drag & drop files here or',
    'ticket.dropFilesHere': 'Drop files here',
    'ticket.browseFiles': 'Browse files',
    'ticket.imageUploadInfo': 'PNG, JPG, or JPEG up to 10MB each. Images upload after ticket creation.',
    'ticket.selectedFiles': 'Selected:',
    'ticket.clearAll': 'Clear all',
    'ticket.remove': 'Remove',
    'ticket.problemTitle': 'Problem Title',
    'ticket.addConciseTitle': 'Add a concise problem title',
    'ticket.describeAbnormalFinding': 'Describe the abnormal finding in detail',
    'ticket.selectSeverity': 'Select severity',
    'ticket.selectPriority': 'Select priority',
    'ticket.submitReport': 'Submit Report',
    'ticket.creating': 'Creating…',
    'ticket.uploadingImages': 'Uploading images…',
    'ticket.ticketNumber': 'Ticket #',
    'ticket.createdBy': 'Created By',
    'ticket.assignedTo': 'Assigned To',
    'ticket.unassigned': 'Unassigned',
    'ticket.to': 'to',
    'ticket.of': 'of',
    'ticket.export': 'Export',
    'ticket.exportComingSoon': 'Export (coming soon)',
    'ticket.exportTickets': 'Export tickets to CSV',
    'ticket.noTicketsToExport': 'No tickets to export',
    'ticket.exportSuccess': 'Tickets exported successfully',
    'ticket.ticketNotFound': 'Ticket Not Found',
    'ticket.ticketNotFoundDescription': 'The requested ticket could not be found.',
    'ticket.backToTickets': 'Back to Tickets',
    'ticket.accept': 'Accept',
    'ticket.overrideAccept': 'Override & Accept',
    'ticket.finalReject': 'Final Reject',
    'ticket.complete': 'Complete',
    'ticket.escalate': 'Escalate',
    'ticket.reassign': 'Reassign',
    'ticket.imageEvidence': 'Image Evidence',
    'ticket.before': 'Before',
    'ticket.after': 'After',
    'ticket.photo': 'photo',
    'ticket.photos': 'photos',
    'ticket.noBeforeImages': 'No before images uploaded yet.',
    'ticket.noAfterImages': 'No after images uploaded yet.',
    'ticket.addProblemEvidence': 'Add problem evidence',
    'ticket.shareImprovementResults': 'Share improvement results',
    'ticket.dragDropOrChoose': 'Drag & drop or choose files to upload.',
    'ticket.uploading': 'Uploading...',
    'ticket.upload': 'Upload',
    'ticket.image': 'image',
    'ticket.images': 'images',
    'ticket.uploadDisabled': 'Upload disabled for closed or rejected tickets.',
    'ticket.afterGalleryUnlock': 'After gallery will unlock once this ticket is accepted or moves to in-progress.',
    'ticket.commentPlaceholder': 'Share an update or ask a question...',
    'ticket.failedToAddComment': 'Failed to add comment',
    'ticket.postComment': 'Post Comment',
    'ticket.ticketInformation': 'Ticket Information',
    'ticket.location': 'Location',
    'ticket.noLocationDetails': 'No location details recorded.',
    'ticket.hours': 'hours',
    'ticket.workflowTimeline': 'Workflow Timeline',
    'ticket.ticketCreated': 'Ticket Created',
    'ticket.by': 'by',
    'ticket.ticketAssigned': 'Ticket Assigned',
    'ticket.statusChangedTo': 'Status Changed to',
    'ticket.rejectionReason': 'Rejection Reason *',
    'ticket.closeReason': 'Close Reason',
    'ticket.reopenReason': 'Reopen Reason',
    'ticket.notes': 'Notes',
    'ticket.rejectionReasonRequired': 'Rejection reason is required',
    'ticket.scheduledCompleteDate': 'Scheduled Complete Date *',
    'ticket.scheduledCompleteDateRequired': 'Scheduled completion date is required',
    'ticket.downtimeAvoidanceHours': 'Downtime Avoidance (hours) *',
    'ticket.costAvoidanceTHB': 'Cost Avoidance (THB) *',
    'ticket.selectFailureMode': 'Select failure mode',
    'ticket.satisfactionRating': 'Satisfaction Rating (1-5)',
    'ticket.newAssignee': 'New Assignee *',
    'ticket.searchL2L3User': 'Search L2/L3 user by name/email',
    'ticket.searching': 'Searching...',
    'ticket.noUsersFound': 'No users found',
    'ticket.pleaseSelectNewAssignee': 'Please select a new assignee',
    'ticket.selectedUserId': 'Selected user ID',
    'ticket.escalateToL3User': 'Escalate To L3 User',
    'ticket.searchL3User': 'Search L3 user by name/email',
    'ticket.noL3UsersFound': 'No L3 users found',
    'ticket.selectedL3UserId': 'Selected L3 user ID',
    'ticket.finalRejectionMessage': 'This will be a final rejection.',
    'ticket.rejectionL3ReviewMessage': 'This rejection will be sent to L3 for review.',
    'ticket.working': 'Working...',
    'ticket.chooseFiles': 'Choose Files',
    'ticketManagement.title': 'Abnormal Finding Report',
    'ticketManagement.createTicket': 'Report Abnormal',
    // Dashboard specific
    'dashboard.abnormalReport': 'Abnormal Report Dashboard',
    'dashboard.totalTickets': 'Total Tickets',
    'dashboard.closedTickets': 'Closed Tickets',
    'dashboard.pendingTickets': 'Pending Tickets',
    'dashboard.totalDowntimeAvoidance': 'Total Downtime Avoidance',
    'dashboard.totalCostAvoidance': 'Total Cost Avoidance',
    'dashboard.topReporter': 'Top Reporter',
    'dashboard.topCostSaver': 'Top Cost Saver',
    'dashboard.topDowntimeSaver': 'Top Downtime Saver',
    'dashboard.participation': 'Participation',
    'dashboard.totalTicketsCountPerPeriod': 'Total Tickets Count Per Period',
    'dashboard.uniqueReporterCoverageRate': 'Unique Reporter & Coverage Rate',
    'dashboard.whoActiveArea': 'Who Active (Area) - Top 10',
    'dashboard.whoActiveUser': 'Who Active (User) - Top 10',
    'dashboard.whenActive': 'When Active - Calendar Heatmap',
    'dashboard.impactAndValue': 'Impact and Value',
    'dashboard.downtimeAvoidanceTrend': 'Downtime Avoidance Trend',
    'dashboard.costAvoidance': 'Cost Avoidance',
    'dashboard.downtimeImpactLeaderboardArea': 'Downtime Impact Leaderboard (Area)',
    'dashboard.costImpactLeaderboardArea': 'Cost Impact Leaderboard (Area)',
    'dashboard.downtimeImpactLeaderboardReporter': 'Downtime Impact Leaderboard (Reporter) - Top 10',
    'dashboard.costImpactLeaderboardReporter': 'Cost Impact Leaderboard (Reporter) - Top 10',
    'dashboard.downtimeImpactByFailureMode': 'Downtime Impact by Failure Mode',
    'dashboard.costImpactByFailureMode': 'Cost Impact by Failure Mode',
    'dashboard.speed': 'Speed',
    'dashboard.ticketAverageResolveDuration': 'Ticket Average Resolve Duration/Case',
    'dashboard.ticketAverageResolveDurationByUser': 'Ticket Average Resolve Duration/Case (By User)',
    'dashboard.ontimeRateByArea': 'Ontime Rate (By Area)',
    'dashboard.ontimeRateByUser': 'Ontime Rate (By User)',
    'dashboard.filters': 'Filters',
    'dashboard.globalFilters': 'Global Filters',
    'dashboard.timeRange': 'Time Range',
    'dashboard.year': 'Year',
    'dashboard.period': 'Period',
    'dashboard.area': 'Area',
    'dashboard.allAreas': 'All Areas',
    'dashboard.thisYear': 'This Year',
    'dashboard.lastYear': 'Last Year',
    'dashboard.thisPeriod': 'This Period',
    'dashboard.selectPeriod': 'Select Period',
    'dashboard.range': 'Range',
    'dashboard.close': 'Close',
    'dashboard.clickToExpand': 'Click to expand →',
    'dashboard.loadingAreas': 'Loading areas...',
    'dashboard.errorLoadingData': 'Error loading data:',
    'dashboard.tickets': 'Tickets',
    'dashboard.target': 'Target',
    'dashboard.uniqueReporters': 'Unique Reporters',
    'dashboard.coverageRate': 'Coverage Rate (%)',
    'dashboard.hours': 'Hours',
    'dashboard.hoursSaved': 'Hours Saved',
    'dashboard.costAvoided': 'Cost Avoided',
    'dashboard.costPerCase': 'Cost per Case (THB/Case)',
    'dashboard.costAvoidanceTHB': 'Cost Avoidance (THB)',
    'dashboard.downtimeHours': 'Downtime Hours',
    'dashboard.caseCount': 'Case Count',
    'dashboard.failureModeCode': 'Failure Mode Code',
    'dashboard.failureModeName': 'Failure Mode Name',
    'dashboard.averageResolveTime': 'Average Resolve Time',
    'dashboard.ticketCount': 'Ticket Count',
    'dashboard.ontimeRate': 'Ontime Rate',
    'dashboard.totalCompleted': 'Total Completed',
    'dashboard.ontimeCompleted': 'Ontime Completed',
    'dashboard.percentage': 'Percentage (%)',
    'dashboard.ticketsReported': 'Tickets Reported',
    'dashboard.ticketsSaved': 'Tickets Saved',
    'dashboard.noData': 'No Data',
    'dashboard.newActivity': 'New Activity',
    'dashboard.activityStopped': 'Activity Stopped',
    'dashboard.noChange': 'No Change',
    'dashboard.increase': 'Increase',
    'dashboard.decrease': 'Decrease',
    'dashboard.less': 'Less',
    'dashboard.more': 'More',
    'dashboard.noDataAvailable': 'No data available',
    'dashboard.clickedOn': 'Clicked on',
    'dashboard.ticketsOnDate': 'tickets',
  },
  th: {
    // Common
    'common.loading': 'กำลังโหลด...',
    'common.error': 'ข้อผิดพลาด',
    'common.success': 'สำเร็จ',
    'common.cancel': 'ยกเลิก',
    'common.save': 'บันทึก',
    'common.edit': 'แก้ไข',
    'common.delete': 'ลบ',
    'common.confirm': 'ยืนยัน',
    'common.back': 'กลับ',
    'common.next': 'ถัดไป',
    'common.previous': 'ก่อนหน้า',
    'common.warning': 'คำเตือน',
    'common.search': 'ค้นหาปัญหา',
    
    // Navigation
    'nav.dashboard': 'แดชบอร์ด',
    'nav.tickets': 'งาน',
    'nav.machines': 'เครื่องจักร',
    'nav.reports': 'รายงาน',
    'nav.users': 'ผู้ใช้',
    'nav.settings': 'ตั้งค่า',
    
    // Authentication
    'auth.login': 'เข้าสู่ระบบ',
    'auth.logout': 'ออกจากระบบ',
    'auth.register': 'ลงทะเบียน',
    'auth.username': 'ชื่อผู้ใช้',
    'auth.password': 'รหัสผ่าน',
    'auth.email': 'อีเมล',
    'auth.firstName': 'ชื่อ',
    'auth.lastName': 'นามสกุล',
    'auth.employeeID': 'รหัสพนักงาน',
    'auth.department': 'แผนก',
    'auth.shift': 'กะ',
    'auth.currentPassword': 'รหัสผ่านปัจจุบัน',
    'auth.newPassword': 'รหัสผ่านใหม่',
    'auth.confirmPassword': 'ยืนยันรหัสผ่าน',
    'auth.changePassword': 'เปลี่ยนรหัสผ่าน',
    'auth.forgotPassword': 'ลืมรหัสผ่าน?',
    'auth.rememberMe': 'จดจำฉัน',
    'auth.loginSuccess': 'เข้าสู่ระบบสำเร็จ',
    'auth.logoutSuccess': 'ออกจากระบบสำเร็จ',
    'auth.registrationSuccess': 'ลงทะเบียนสำเร็จ',
    'auth.passwordChangeSuccess': 'เปลี่ยนรหัสผ่านสำเร็จ',
    
    // User roles
    'role.l1_operator': 'ผู้ปฏิบัติการ L1',
    'role.l2_engineer': 'วิศวกร L2',
    'role.l3_manager': 'ผู้จัดการ L3',
    
    // Dashboard
    'dashboard.welcome': 'ยินดีต้อนรับ',
    
    // Profile
    'profile.title': 'โปรไฟล์ผู้ใช้',
    'profile.personalInfo': 'ข้อมูลส่วนตัว',
    'profile.workInfo': 'ข้อมูลการทำงาน',
    'profile.lastLogin': 'เข้าสู่ระบบล่าสุด',
    'profile.memberSince': 'เป็นสมาชิกตั้งแต่',
    'profile.profileInformation': 'ข้อมูลโปรไฟล์',
    'profile.changeProfilePicture': 'เปลี่ยนรูปโปรไฟล์',
    'profile.upload': 'อัปโหลด',
    'profile.chooseFile': 'เลือกไฟล์',
    'profile.firstName': 'ชื่อ',
    'profile.lastName': 'นามสกุล',
    'profile.email': 'อีเมล',
    'profile.phone': 'โทรศัพท์',
    'profile.jobTitle': 'ตำแหน่ง',
    'profile.department': 'แผนก',
    'profile.group': 'กลุ่ม',
    'profile.personCode': 'รหัสพนักงาน',
    'profile.saveChanges': 'บันทึกการเปลี่ยนแปลง',
    'profile.profileUpdated': 'อัปเดตโปรไฟล์แล้ว',
    'profile.failedToUpdateProfile': 'ไม่สามารถอัปเดตโปรไฟล์ได้',
    'profile.avatarUpdated': 'อัปเดตรูปโปรไฟล์แล้ว',
    'profile.failedToUploadAvatar': 'ไม่สามารถอัปโหลดรูปโปรไฟล์ได้',
    'profile.lineNotifications': 'การแจ้งเตือน LINE',
    'profile.lineUserId': 'LINE User ID (สำหรับการแจ้งเตือน)',
    'profile.enterLineId': 'กรอกรหัส LineID ของคุณ',
    'profile.sendTestLineNotification': 'ส่งการแจ้งเตือน LINE ทดสอบ',
    'profile.ensureLineIdSet': 'ตรวจสอบให้แน่ใจว่ารหัส LineID ของคุณถูกตั้งค่าไว้ด้านบน',
    'profile.testNotificationSent': 'ส่งการแจ้งเตือนทดสอบไปยัง LINE ของคุณแล้ว',
    'profile.failedToSendTestNotification': 'ไม่สามารถส่งการแจ้งเตือนทดสอบได้',
    'profile.changePassword': 'เปลี่ยนรหัสผ่าน',
    'profile.currentPassword': 'รหัสผ่านปัจจุบัน',
    'profile.newPassword': 'รหัสผ่านใหม่',
    'profile.passwordChanged': 'เปลี่ยนรหัสผ่านแล้ว',
    'profile.failedToChangePassword': 'ไม่สามารถเปลี่ยนรหัสผ่านได้',
    'profile.lineHelpTitle': 'วิธีรับ LINE User ID ของคุณ',
    'profile.lineHelpDescription': 'ทำตามขั้นตอนเหล่านี้เพื่อรับ LINE User ID สำหรับการแจ้งเตือน:',
    'profile.step1Title': 'เพิ่มบัญชี LINE Official ของเรา',
    'profile.step1Description': 'สแกน QR code ด้านล่างหรือคลิกลิงก์เพื่อเพิ่มบัญชี LINE ของเราเป็นเพื่อน',
    'profile.addLineFriend': 'เพิ่มเพื่อน LINE',
    'profile.step2Title': 'ส่งข้อความ "Line ID"',
    'profile.step2Description': 'เปิดแชทกับบัญชี LINE ของเราและส่งข้อความ:',
    'profile.step3Title': 'คัดลอก User ID ของคุณ',
    'profile.step3Description': 'คัดลอก User ID ที่ได้รับและวางในช่องด้านบน',
    'profile.gotIt': 'เข้าใจแล้ว!',
    'profile.cropAvatar': 'ตัดรูปโปรไฟล์',
    'profile.zoom': 'ซูม',
    'profile.cancel': 'ยกเลิก',
    'profile.apply': 'ใช้',
    'profile.failedToCropImage': 'ไม่สามารถตัดรูปภาพได้',
    
    // Settings
    'settings.title': 'ตั้งค่า',
    'settings.appearance': 'ลักษณะ',
    'settings.language': 'ภาษา',
    'settings.notifications': 'การแจ้งเตือน',
    'settings.security': 'ความปลอดภัย',
    
    // Theme
    'theme.light': 'สว่าง',
    'theme.dark': 'มืด',
    'theme.auto': 'อัตโนมัติ',
    
    // Language
    'language.english': 'English',
    'language.thai': 'ไทย',
    
    // Errors
    'error.invalidCredentials': 'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง',
    'error.userNotFound': 'ไม่พบผู้ใช้',
    'error.unauthorized': 'การเข้าถึงไม่ได้รับอนุญาต',
    'error.forbidden': 'การเข้าถึงถูกห้าม',
    'error.notFound': 'ไม่พบหน้า',
    'error.serverError': 'ข้อผิดพลาดของเซิร์ฟเวอร์',
    'error.networkError': 'ข้อผิดพลาดเครือข่าย',
    'error.validationError': 'ข้อผิดพลาดการตรวจสอบ',
    
    // Validation
    'validation.required': 'กรุณากรอกข้อมูลในช่องนี้',
    'validation.email': 'กรุณากรอกอีเมลที่ถูกต้อง',
    'validation.passwordLength': 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',
    'validation.passwordMatch': 'รหัสผ่านไม่ตรงกัน',
    'validation.usernameLength': 'ชื่อผู้ใช้ต้องมีอย่างน้อย 3 ตัวอักษร',
    
    // Homepage specific
    'homepage.welcome': 'ยินดีต้อนรับ',
    'homepage.quickActions': 'ทางลัด',
    'homepage.pendingTickets': 'งานที่รอดำเนินการ',
    'homepage.personal': 'ส่วนตัว',
    'homepage.team': 'ทีม',
    'homepage.createTicket': 'รายงานความผิดปกติ',
    'homepage.viewTickets': 'ดูรายงานทั้งหมด',
    'homepage.reportNewIssue': 'รายงานความผิดปกติหรือคำขอใหม่',
    'homepage.checkTicketStatus': 'ตรวจสอบสถานะงานของคุณ',
    'homepage.loadingPendingTickets': 'กำลังโหลดงานที่รอดำเนินการ...',
    'homepage.errorLoadingTickets': 'ข้อผิดพลาดในการโหลดงาน',
    'homepage.noPendingTickets': 'ไม่มีงานที่รอดำเนินการ',
    'homepage.allTicketsUpToDate': 'งานทั้งหมดของคุณเป็นปัจจุบันแล้ว!',
    'homepage.youCreatedThisTicket': 'คุณรายงานความผิดปกตินี้',
    'homepage.requiresYourApproval': 'ต้องการการอนุมัติจากคุณ',
    'homepage.viewOnly': 'ดูเท่านั้น',
    'homepage.myCompleteCasesPerPeriod': 'จำนวนเคสที่ฉันแก้ไขเสร็จตามช่วงเวลา',
    'homepage.myReportCasePerPeriod': 'จำนวนเคสที่ฉันรายงานตามช่วงเวลา',
    'homepage.setupKPI': 'ตั้งค่า KPI',
    'homepage.errorLoadingChartData': 'ข้อผิดพลาดในการโหลดข้อมูลแผนภูมิ',
    'homepage.noCompletedTicketData': 'ไม่มีข้อมูลงานที่เสร็จสิ้น',
    'homepage.completeSomeTickets': 'ทำงานให้เสร็จเพื่อดูประสิทธิภาพของคุณ!',
    'homepage.noTicketDataAvailable': 'ไม่มีข้อมูลงาน',
    'homepage.startCreatingTickets': 'เริ่มรายงานความผิดปกติเพื่อดูประสิทธิภาพของคุณ!',
    'homepage.asReporter': 'ในฐานะผู้รายงาน (ฉันช่วยโดยการรายงาน)',
    'homepage.asActionPerson': 'ในฐานะผู้ดำเนินการ (ฉันช่วยโดยการแก้ไข)',
    'homepage.errorLoadingKPIData': 'ข้อผิดพลาดในการโหลดข้อมูล KPI',
    'homepage.loadingPersonalMetrics': 'กำลังโหลดเมตริกส่วนตัว...',
    'homepage.noKPIDataAvailable': 'ไม่มีข้อมูล KPI',
    'homepage.myReportsCreated': 'จำนวนเคสที่ฉันรายงาน',
    'homepage.downtimeAvoidedByMyReports': 'เวลาหยุดทำงานที่หลีกเลี่ยงได้จากรายงานของฉัน',
    'homepage.costAvoidedByMyReports': 'ต้นทุนที่หลีกเลี่ยงได้จากรายงานของฉัน',
    'homepage.casesIFixed': 'จำนวนเคสที่ฉันแก้ไข',
    'homepage.downtimeIFixed': 'เวลาหยุดทำงานที่หลีกเลี่ยงได้จากการแก้ไข',
    'homepage.costIFixed': 'ต้นทุนที่หลีกเลี่ยงได้จากการแก้ไข',
    'homepage.noChange': 'ไม่มีการเปลี่ยนแปลง',
    'homepage.teamPerformance': 'ประสิทธิภาพทีม',
    'homepage.teamPerformanceComingSoon': 'เมตริกประสิทธิภาพทีมจะมาเร็วๆ นี้...',
    'homepage.filters': 'ตัวกรอง',
    'homepage.range': 'ช่วง',
    'homepage.currentSelection': 'การเลือกปัจจุบัน',
    'homepage.thisYear': 'ปีนี้',
    'homepage.lastYear': 'ปีที่แล้ว',
    'homepage.thisPeriod': 'ช่วงเวลา',
    'homepage.completedTickets': 'งานที่เสร็จสิ้น',
    'homepage.target': 'เป้าหมาย',
    'homepage.myTickets': 'งานของฉัน',
    'homepage.failedToFetchPendingTickets': 'ไม่สามารถดึงงานที่รอดำเนินการได้',
    'homepage.failedToFetchPersonalTicketData': 'ไม่สามารถดึงข้อมูลงานส่วนตัวได้',
    'homepage.failedToFetchPersonalCompletedTicketData': 'ไม่สามารถดึงข้อมูลงานที่เสร็จสิ้นส่วนตัวได้',
    'homepage.failedToFetchPersonalKPIData': 'ไม่สามารถดึงข้อมูล KPI ส่วนตัวได้',
    
    // Personal KPI Modal
    'personalKPI.title': 'การตั้งค่าเป้าหมาย KPI ส่วนตัว',
    'personalKPI.reportCases': 'กรณีรายงาน',
    'personalKPI.fixCases': 'กรณีแก้ไข',
    'personalKPI.error': 'ข้อผิดพลาด',
    'personalKPI.success': 'สำเร็จ',
    'personalKPI.validationError': 'ข้อผิดพลาดการตรวจสอบ',
    'personalKPI.failedToFetchExistingTargets': 'ไม่สามารถดึงเป้าหมายที่มีอยู่ได้',
    'personalKPI.userInformationNotAvailable': 'ข้อมูลผู้ใช้ไม่พร้อมใช้งาน',
    'personalKPI.failedToSavePersonalTargets': 'ไม่สามารถบันทึกเป้าหมายส่วนตัวได้',
    'personalKPI.user': 'ผู้ใช้',
    'personalKPI.personNo': 'รหัสพนักงาน',
    'personalKPI.year': 'ปี',
    'personalKPI.unit': 'หน่วย',
    'personalKPI.case': 'เคส',
    'personalKPI.thb': 'บาท',
    'personalKPI.percent': 'เปอร์เซ็นต์',
    'personalKPI.existingTargetsWarning': 'คุณมีเป้าหมายที่ตั้งไว้แล้วสำหรับ {type} ในปี {year} การบันทึกค่าใหม่จะแทนที่เป้าหมายเดิม',
    'personalKPI.periodValues': 'ค่าเป้าหมายตามช่วงเวลา',
    'personalKPI.copyP1ToAll': 'คัดลอก P1 ไปทุกช่วงเวลา',
    'personalKPI.resetForm': 'รีเซ็ตฟอร์ม',
    'personalKPI.cancel': 'ยกเลิก',
    'personalKPI.saveTargets': 'บันทึกเป้าหมาย',
    'personalKPI.saving': 'กำลังบันทึก...',
    'personalKPI.fillAllPeriods': 'กรุณากรอกค่าสำหรับทุกช่วงเวลา: {periods}',
    'personalKPI.targetsSavedSuccess': 'บันทึกเป้าหมายส่วนตัวสำเร็จสำหรับ {type} ในปี {year}',
    'personalKPI.report': 'รายงาน',
    'personalKPI.fix': 'แก้ไข',
    'personalFilter.title': 'ตัวกรองประสิทธิภาพส่วนตัว',
    'personalFilter.timeRange': 'ช่วงเวลา',
    'personalFilter.selectTimeRange': 'เลือกช่วงเวลา',
    'personalFilter.thisYear': 'ปีนี้',
    'personalFilter.lastYear': 'ปีที่แล้ว',
    'personalFilter.thisPeriod': 'ช่วงเวลานี้',
    'personalFilter.selectPeriod': 'เลือกช่วงเวลา',
    'personalFilter.year': 'ปี',
    'personalFilter.period': 'ช่วงเวลา',
    'personalFilter.applyFilters': 'ใช้ตัวกรอง',
    
    // Common chart labels
    'chart.completedTickets': 'งานที่เสร็จสิ้น',
    'chart.target': 'เป้าหมาย',
    'chart.myTickets': 'รายงานของฉัน',
    
    // Ticket Management
    'ticket.create': 'รายงานความผิดปกติ',
    'ticket.edit': 'แก้ไขงาน',
    'ticket.view': 'ดูงาน',
    'ticket.title': 'หัวข้อ',
    'ticket.description': 'รายละเอียด',
    'ticket.status': 'สถานะ',
    'ticket.priority': 'ความสำคัญ',
    'ticket.severity': 'ความรุนแรง',
    'ticket.pucode': 'PUCODE',
    'ticket.area': 'พื้นที่',
    'ticket.created': 'สร้างเมื่อ',
    'ticket.updated': 'อัปเดตเมื่อ',
    'ticket.assignee': 'ผู้รับผิดชอบ',
    'ticket.reporter': 'ผู้รายงาน',
    'ticket.reportAbnormalFinding': 'รายงานความผิดปกติ',
    'ticket.briefDescription': 'คำอธิบายสั้นๆ เกี่ยวกับความผิดปกติ',
    'ticket.detailedDescription': 'คำอธิบายรายละเอียดเกี่ยวกับความผิดปกติ รวมถึงอาการและการสังเกต',
    'ticket.titleRequired': 'กรุณากรอกหัวข้อ',
    'ticket.descriptionRequired': 'กรุณากรอกรายละเอียด',
    'ticket.pucodeRequired': 'กรุณากรอก PUCODE',
    'ticket.machineName': 'ชื่อเครื่องจักร', // Added machine name
    'ticket.ticketCreatedSuccess': 'สร้างงานสำเร็จ',
    'ticket.ticketUpdatedSuccess': 'อัปเดตงานสำเร็จ',
    'ticket.failedToCreateTicket': 'ไม่สามารถสร้างงานได้',
    'ticket.failedToUpdateTicket': 'ไม่สามารถอัปเดตงานได้',
    'ticket.failedToFetchTickets': 'ไม่สามารถดึงข้อมูลงานได้',
    'ticket.noTicketsFound': 'ไม่พบรายงาน',
    'ticket.loadingTickets': 'กำลังโหลดงาน...',
    'ticket.errorLoadingTickets': 'ข้อผิดพลาดในการโหลดงาน',
    'ticket.searchTickets': 'ค้นหางาน...',
    'ticket.filterByStatus': 'กรองตามสถานะ',
    'ticket.filterByPriority': 'กรองตามความสำคัญ',
    'ticket.filterBySeverity': 'กรองตามความรุนแรง',
    'ticket.allStatuses': 'ทุกสถานะ',
    'ticket.allPriorities': 'ทุกความสำคัญ',
    'ticket.allSeverities': 'ทุกความรุนแรง',
    'ticket.allAreas': 'ทุกพื้นที่',
    'ticket.open': 'เปิด',
    'ticket.assigned': 'มอบหมายแล้ว',
    'ticket.inProgress': 'กำลังดำเนินการ',
    'ticket.pending': 'รอดำเนินการ',
    'ticket.resolved': 'แก้ไขแล้ว',
    'ticket.closed': 'ปิด',
    'ticket.cancelled': 'ยกเลิก',
    'ticket.low': 'ต่ำ',
    'ticket.medium': 'ปานกลาง',
    'ticket.high': 'สูง',
    'ticket.critical': 'วิกฤต',
    'ticket.normal': 'ปกติ',
    'ticket.urgent': 'ด่วน',
    'ticket.costAvoidance': 'ต้นทุนที่หลีกเลี่ยงได้',
    'ticket.downtimeAvoidance': 'เวลาหยุดทำงานที่หลีกเลี่ยงได้ (ชั่วโมง)',
    'ticket.failureMode': 'ลักษณะปัญหา',
    'ticket.attachments': 'ไฟล์แนบ',
    'ticket.addAttachment': 'เพิ่มไฟล์แนบ',
    'ticket.removeAttachment': 'ลบไฟล์แนบ',
    'ticket.comments': 'ความคิดเห็น',
    'ticket.addComment': 'เพิ่มความคิดเห็น',
    'ticket.noComments': 'ยังไม่มีความคิดเห็น',
    'ticket.history': 'ประวัติ',
    'ticket.timeline': 'ไทม์ไลน์',
    'ticket.actions': 'การดำเนินการ',
    'ticket.approve': 'อนุมัติ',
    'ticket.reject': 'ปฏิเสธ',
    'ticket.assign': 'มอบหมาย',
    'ticket.unassign': 'ยกเลิกการมอบหมาย',
    'ticket.close': 'ปิด',
    'ticket.reopen': 'เปิดใหม่',
    'ticket.duplicate': 'ทำซ้ำ',
    'ticket.duplicateTicket': 'ทำซ้ำงาน',
    'ticket.originalTicket': 'งานต้นฉบับ',
    'ticket.relatedTickets': 'งานที่เกี่ยวข้อง',
    'ticket.dependencies': 'การพึ่งพา',
    'ticket.tags': 'แท็ก',
    'ticket.addTag': 'เพิ่มแท็ก',
    'ticket.removeTag': 'ลบแท็ก',
    'ticket.wizard': 'ตัวช่วยสร้างงาน',
    'ticket.wizardStep1': 'ขั้นตอนที่ 1: ข้อมูลพื้นฐาน',
    'ticket.wizardStep2': 'ขั้นตอนที่ 2: รายละเอียด',
    'ticket.wizardStep3': 'ขั้นตอนที่ 3: ตรวจสอบ',
    'ticket.wizardNext': 'ถัดไป',
    'ticket.wizardPrevious': 'ก่อนหน้า',
    'ticket.wizardFinish': 'เสร็จสิ้น',
    'ticket.wizardCancel': 'ยกเลิก',
    'ticket.wizardBack': 'กลับ',
    'ticket.wizardReview': 'ตรวจสอบ',
    'ticket.wizardConfirm': 'ยืนยัน',
    'ticket.wizardSuccess': 'สร้างงานสำเร็จ!',
    'ticket.wizardError': 'ข้อผิดพลาดในการสร้างงาน',
    'ticket.wizardValidationError': 'กรุณากรอกข้อมูลในช่องที่จำเป็น',
    'ticket.wizardSelectPlant': 'เลือกโรงงาน',
    'ticket.wizardSelectArea': 'เลือกพื้นที่',
    'ticket.wizardSelectLine': 'เลือกไลน์',
    'ticket.wizardSelectMachine': 'เลือกเครื่องจักร',
    'ticket.wizardSelectPUCODE': 'เลือก PUCODE',
    'ticket.wizardSelectFailureMode': 'เลือกลักษณะปัญหา',
    'ticket.wizardUploadImages': 'อัปโหลดรูปภาพ',
    'ticket.wizardDragDropImages': 'ลากและวางรูปภาพที่นี่ หรือคลิกเพื่อเลือก',
    'ticket.wizardImagePreview': 'ตัวอย่างรูปภาพ',
    'ticket.wizardRemoveImage': 'ลบรูปภาพ',
    'ticket.wizardMaxImages': 'อัปโหลดได้สูงสุด 5 รูป',
    'ticket.wizardImageSize': 'ขนาดรูปภาพควรน้อยกว่า 5MB',
    'ticket.wizardImageFormat': 'รองรับเฉพาะรูปแบบ JPG, PNG, GIF',
    'ticket.deleteConfirm': 'คุณแน่ใจหรือไม่ว่าต้องการลบงานนี้?',
    'ticket.ticketDeletedSuccess': 'ลบงานสำเร็จ',
    'ticket.failedToDeleteTicket': 'ไม่สามารถลบงานได้',
    'ticket.warning': 'คำเตือน',
    'ticket.fileSkipped': 'ข้ามไฟล์บางไฟล์ รับเฉพาะไฟล์รูปภาพเท่านั้น',
    'ticket.fileSizeExceeded': 'ไฟล์ถูกข้าม ขนาดไฟล์สูงสุด 10MB',
    'ticket.searchMachines': 'กำลังค้นหา...',
    'ticket.failedToSearchMachines': 'ไม่สามารถค้นหาเครื่องจักรได้ กรุณาลองใหม่',
    'ticket.selectMachine': 'กรุณาเลือกเครื่องจักร',
    'ticket.atLeastOneAttachment': 'ต้องมีไฟล์แนบอย่างน้อย 1 ไฟล์',
    'ticket.selectedMachine': 'เครื่องจักรที่เลือก',
    'ticket.typeToSearch': 'พิมพ์อย่างน้อย 2 ตัวอักษรเพื่อค้นหา แสดงเฉพาะ PUCODE 5 ส่วน (Plant-Area-Line-Machine-Number) สำหรับการค้นหาความผิดปกติ',
    'ticket.attachImages': 'แนบรูปภาพ (ก่อน)',
    'ticket.dragDropFiles': 'ลากและวางไฟล์ที่นี่ หรือ',
    'ticket.dropFilesHere': 'วางไฟล์ที่นี่',
    'ticket.browseFiles': 'เลือกไฟล์',
    'ticket.imageUploadInfo': 'PNG, JPG หรือ JPEG สูงสุด 10MB ต่อไฟล์ รูปภาพจะอัปโหลดหลังจากสร้างงานแล้ว',
    'ticket.selectedFiles': 'เลือกแล้ว:',
    'ticket.clearAll': 'ลบทั้งหมด',
    'ticket.remove': 'ลบ',
    'ticket.problemTitle': 'หัวข้อปัญหา',
    'ticket.addConciseTitle': 'เพิ่มหัวข้อปัญหาที่กระชับ',
    'ticket.describeAbnormalFinding': 'อธิบายความผิดปกติอย่างละเอียด',
    'ticket.selectSeverity': 'เลือกความรุนแรง',
    'ticket.selectPriority': 'เลือกความสำคัญ',
    'ticket.submitReport': 'ส่งรายงาน',
    'ticket.creating': 'กำลังสร้าง...',
    'ticket.uploadingImages': 'กำลังอัปโหลดรูปภาพ...',
    'ticket.ticketNumber': 'หมายเลขงาน',
    'ticket.createdBy': 'สร้างโดย',
    'ticket.assignedTo': 'มอบหมายให้',
    'ticket.unassigned': 'ยังไม่ได้มอบหมาย',
    'ticket.to': 'ถึง',
    'ticket.of': 'จาก',
    'ticket.export': 'ส่งออก',
    'ticket.exportComingSoon': 'ส่งออก (เร็วๆ นี้)',
    'ticket.exportTickets': 'ส่งออกงานเป็นไฟล์ CSV',
    'ticket.noTicketsToExport': 'ไม่มีงานที่จะส่งออก',
    'ticket.exportSuccess': 'ส่งออกงานเรียบร้อยแล้ว',
    'ticket.ticketNotFound': 'ไม่พบรายงาน',
    'ticket.ticketNotFoundDescription': 'ไม่พบรายงานที่ร้องขอ',
    'ticket.backToTickets': 'กลับไปยังรายการงาน',
    'ticket.accept': 'ยอมรับ',
    'ticket.overrideAccept': 'ข้ามและยอมรับ',
    'ticket.finalReject': 'ปฏิเสธขั้นสุดท้าย',
    'ticket.complete': 'เสร็จสิ้น',
    'ticket.escalate': 'ส่งต่อ',
    'ticket.reassign': 'มอบหมายใหม่',
    'ticket.imageEvidence': 'หลักฐานรูปภาพ',
    'ticket.before': 'ก่อน',
    'ticket.after': 'หลัง',
    'ticket.photo': 'รูป',
    'ticket.photos': 'รูป',
    'ticket.noBeforeImages': 'ยังไม่ได้อัปโหลดรูปภาพก่อน',
    'ticket.noAfterImages': 'ยังไม่ได้อัปโหลดรูปภาพหลัง',
    'ticket.addProblemEvidence': 'เพิ่มหลักฐานปัญหา',
    'ticket.shareImprovementResults': 'แชร์ผลการปรับปรุง',
    'ticket.dragDropOrChoose': 'ลากและวางหรือเลือกไฟล์เพื่ออัปโหลด',
    'ticket.uploading': 'กำลังอัปโหลด...',
    'ticket.upload': 'อัปโหลด',
    'ticket.image': 'รูปภาพ',
    'ticket.images': 'รูปภาพ',
    'ticket.uploadDisabled': 'ปิดการอัปโหลดสำหรับงานที่ปิดหรือปฏิเสธแล้ว',
    'ticket.afterGalleryUnlock': 'แกลเลอรี่หลังจะปลดล็อกเมื่องานนี้ได้รับการยอมรับหรือเปลี่ยนเป็นกำลังดำเนินการ',
    'ticket.commentPlaceholder': 'แชร์การอัปเดตหรือถามคำถาม...',
    'ticket.failedToAddComment': 'ไม่สามารถเพิ่มความคิดเห็นได้',
    'ticket.postComment': 'โพสต์ความคิดเห็น',
    'ticket.ticketInformation': 'ข้อมูลงาน',
    'ticket.location': 'ตำแหน่ง',
    'ticket.noLocationDetails': 'ไม่มีรายละเอียดตำแหน่ง',
    'ticket.hours': 'ชั่วโมง',
    'ticket.workflowTimeline': 'ไทม์ไลน์การทำงาน',
    'ticket.ticketCreated': 'สร้างงานแล้ว',
    'ticket.by': 'โดย',
    'ticket.ticketAssigned': 'มอบหมายงานแล้ว',
    'ticket.statusChangedTo': 'เปลี่ยนสถานะเป็น',
    'ticket.rejectionReason': 'เหตุผลการปฏิเสธ *',
    'ticket.closeReason': 'เหตุผลการปิด',
    'ticket.reopenReason': 'เหตุผลการเปิดใหม่',
    'ticket.notes': 'หมายเหตุ',
    'ticket.rejectionReasonRequired': 'ต้องระบุเหตุผลการปฏิเสธ',
    'ticket.scheduledCompleteDate': 'วันที่กำหนดเสร็จสิ้น *',
    'ticket.scheduledCompleteDateRequired': 'ต้องระบุวันที่กำหนดเสร็จสิ้น',
    'ticket.downtimeAvoidanceHours': 'เวลาหยุดทำงานที่หลีกเลี่ยงได้ (ชั่วโมง) *',
    'ticket.costAvoidanceTHB': 'ต้นทุนที่หลีกเลี่ยงได้ (บาท) *',
    'ticket.selectFailureMode': 'เลือกลักษณะปัญหา',
    'ticket.satisfactionRating': 'คะแนนความพึงพอใจ (1-5)',
    'ticket.newAssignee': 'ผู้รับผิดชอบใหม่ *',
    'ticket.searchL2L3User': 'ค้นหาผู้ใช้ L2/L3 ตามชื่อ/อีเมล',
    'ticket.searching': 'กำลังค้นหา...',
    'ticket.noUsersFound': 'ไม่พบผู้ใช้',
    'ticket.pleaseSelectNewAssignee': 'กรุณาเลือกผู้รับผิดชอบใหม่',
    'ticket.selectedUserId': 'รหัสผู้ใช้ที่เลือก',
    'ticket.escalateToL3User': 'ส่งต่อให้ผู้ใช้ L3',
    'ticket.searchL3User': 'ค้นหาผู้ใช้ L3 ตามชื่อ/อีเมล',
    'ticket.noL3UsersFound': 'ไม่พบผู้ใช้ L3',
    'ticket.selectedL3UserId': 'รหัสผู้ใช้ L3 ที่เลือก',
    'ticket.finalRejectionMessage': 'นี่จะเป็น การปฏิเสธขั้นสุดท้าย',
    'ticket.rejectionL3ReviewMessage': 'การปฏิเสธนี้จะถูกส่งไปให้ L3 ทบทวน',
    'ticket.working': 'กำลังทำงาน...',
    'ticket.chooseFiles': 'เลือกไฟล์',
    'ticketManagement.title': 'การแจ้งเตือนความผิดปกติ',
    'ticketManagement.createTicket': 'แจ้งความผิดปกติ',
    
    // Dashboard specific
    'dashboard.abnormalReport': 'แดชบอร์ดรายงานความผิดปกติ',
    'dashboard.totalTickets': 'จำนวนรายงานทั้งหมด',
    'dashboard.closedTickets': 'รายงานที่ปิดแล้ว',
    'dashboard.pendingTickets': 'รายงานที่รอดำเนินการ',
    'dashboard.totalDowntimeAvoidance': 'เวลาหยุดทำงานที่หลีกเลี่ยงได้ทั้งหมด',
    'dashboard.totalCostAvoidance': 'ต้นทุนที่หลีกเลี่ยงได้ทั้งหมด',
    'dashboard.topReporter': 'ผู้รายงานยอดเยี่ยม',
    'dashboard.topCostSaver': 'ผู้ประหยัดต้นทุนยอดเยี่ยม',
    'dashboard.topDowntimeSaver': 'ผู้ประหยัดเวลาหยุดทำงานยอดเยี่ยม',
    'dashboard.participation': 'การมีส่วนร่วม',
    'dashboard.totalTicketsCountPerPeriod': 'จำนวนรายงานทั้งหมดต่อช่วงเวลา',
    'dashboard.uniqueReporterCoverageRate': 'ผู้รายงานที่ไม่ซ้ำกันและอัตราการกระจายตัว',
    'dashboard.whoActiveArea': 'พื้นที่ที่พบปัญหา - 10 อันดับแรก',
    'dashboard.whoActiveUser': 'ผู้ที่แจ้งปัญหามากที่สุด 10 อันดับแรก',
    'dashboard.whenActive': 'ลักษณะการกระจายตัวของการรายงานความผิดปกติตามปฏิทิน',
    'dashboard.impactAndValue': 'ผลกระทบและคุณค่า',
    'dashboard.downtimeAvoidanceTrend': 'แนวโน้มการหลีกเลี่ยงเวลาหยุดทำงาน',
    'dashboard.costAvoidance': 'การหลีกเลี่ยงต้นทุน',
    'dashboard.downtimeImpactLeaderboardArea': 'จำนวนเวลาหยุดทำงานที่หลีกเลี่ยงได้ตามพื้นที่',
    'dashboard.costImpactLeaderboardArea': 'จำนวนต้นทุนที่หลีกเลี่ยงได้ตามพื้นที่',
    'dashboard.downtimeImpactLeaderboardReporter': 'จำนวนเวลาหยุดทำงานที่หลีกเลี่ยงได้ รายบุคคล - 10 อันดับแรก',
    'dashboard.costImpactLeaderboardReporter': 'จำนวนต้นทุนที่หลีกเลี่ยงได้ รายบุคคล - 10 อันดับแรก',
    'dashboard.downtimeImpactByFailureMode': 'ผลกระทบเวลาหยุดทำงานตามลักษณะปัญหา',
    'dashboard.costImpactByFailureMode': 'ผลกระทบต้นทุนตามลักษณะปัญหา',
    'dashboard.speed': 'ความเร็ว',
    'dashboard.ticketAverageResolveDuration': 'ระยะเวลาเฉลี่ยในการแก้ไขงาน/เคส',
    'dashboard.ticketAverageResolveDurationByUser': 'ระยะเวลาเฉลี่ยในการแก้ไขงาน/เคส (ตามผู้ใช้)',
    'dashboard.ontimeRateByArea': 'อัตราการทำงานตรงเวลา (ตามพื้นที่)',
    'dashboard.ontimeRateByUser': 'อัตราการทำงานตรงเวลา (ตามผู้ใช้)',
    'dashboard.filters': 'ตัวกรอง',
    'dashboard.globalFilters': 'ตัวกรองทั่วไป',
    'dashboard.timeRange': 'ช่วงเวลา',
    'dashboard.year': 'ปี',
    'dashboard.period': 'ช่วงเวลา',
    'dashboard.area': 'พื้นที่',
    'dashboard.allAreas': 'ทุกพื้นที่',
    'dashboard.thisYear': 'ปีนี้',
    'dashboard.lastYear': 'ปีที่แล้ว',
    'dashboard.thisPeriod': 'ช่วงเวลานี้',
    'dashboard.selectPeriod': 'เลือกช่วงเวลา',
    'dashboard.range': 'ช่วง',
    'dashboard.close': 'ปิด',
    'dashboard.clickToExpand': 'คลิกเพื่อขยาย →',
    'dashboard.loadingAreas': 'กำลังโหลดพื้นที่...',
    'dashboard.errorLoadingData': 'ข้อผิดพลาดในการโหลดข้อมูล:',
    'dashboard.tickets': 'รายงาน',
    'dashboard.target': 'เป้าหมาย',
    'dashboard.uniqueReporters': 'ผู้รายงานที่ไม่ซ้ำกัน',
    'dashboard.coverageRate': 'อัตราการกระจายตัว (%)',
    'dashboard.hours': 'ชั่วโมง',
    'dashboard.hoursSaved': 'ชั่วโมงที่ประหยัดได้',
    'dashboard.costAvoided': 'ต้นทุนที่หลีกเลี่ยงได้',
    'dashboard.costPerCase': 'ต้นทุนต่อเคส (บาท/เคส)',
    'dashboard.costAvoidanceTHB': 'การหลีกเลี่ยงต้นทุน (บาท)',
    'dashboard.downtimeHours': 'ชั่วโมงหยุดทำงาน',
    'dashboard.caseCount': 'จำนวนเคส',
    'dashboard.failureModeCode': 'รหัสลักษณะปัญหา',
    'dashboard.failureModeName': 'ชื่อลักษณะปัญหา',
    'dashboard.averageResolveTime': 'เวลาการแก้ไขเฉลี่ย',
    'dashboard.ticketCount': 'จำนวนรายงาน',
    'dashboard.ontimeRate': 'อัตราการทำงานตรงเวลา',
    'dashboard.totalCompleted': 'เสร็จสิ้นทั้งหมด',
    'dashboard.ontimeCompleted': 'เสร็จสิ้นตรงเวลา',
    'dashboard.percentage': 'เปอร์เซ็นต์ (%)',
    'dashboard.ticketsReported': 'รายงานที่รายงาน',
    'dashboard.ticketsSaved': 'รายงานที่ประหยัดได้',
    'dashboard.noData': 'ไม่มีข้อมูล',
    'dashboard.newActivity': 'กิจกรรมใหม่',
    'dashboard.activityStopped': 'กิจกรรมหยุด',
    'dashboard.noChange': 'ไม่มีการเปลี่ยนแปลง',
    'dashboard.increase': 'เพิ่มขึ้น',
    'dashboard.decrease': 'ลดลง',
    'dashboard.less': 'น้อย',
    'dashboard.more': 'มาก',
    'dashboard.noDataAvailable': 'ไม่มีข้อมูล',
    'dashboard.clickedOn': 'คลิกที่',
    'dashboard.ticketsOnDate': 'รายงาน',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Get language from localStorage or default to 'en'
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'en';
  });

  useEffect(() => {
    // Save language to localStorage
    localStorage.setItem('language', language);
    
    // Set document language
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let translation = translations[language][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        translation = translation.replace(`{${paramKey}}`, String(paramValue));
      });
    }
    
    return translation;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
