name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to deploy'
        required: true
        default: 'both'
        type: choice
        options:
        - frontend
        - backend
        - both
      environment:
        description: 'Environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production

jobs:
  deploy-frontend:
    if: ${{ github.event.inputs.service == 'frontend' || github.event.inputs.service == 'both' }}
    runs-on: [self-hosted, FE]
    environment: staging-frontend
    
    steps:
    - name: Deploy frontend
      working-directory: /opt/mars-app/frontend
      run: |
        ./deploy_frontend.sh ${{ github.event.inputs.environment }}
        
    - name: Verify deployment
      run: |
        docker ps | grep mars-frontend
        echo "Frontend deployment completed successfully"

  deploy-backend:
    if: ${{ github.event.inputs.service == 'backend' || github.event.inputs.service == 'both' }}
    runs-on: [self-hosted, BE]
    environment: staging-backend
    
    steps:
    - name: Deploy backend
      working-directory: /opt/mars-app/backend
      run: |
        ./deploy_backend.sh ${{ github.event.inputs.environment }}
        
    - name: Verify deployment
      run: |
        docker ps | grep mars-backend
        echo "Backend deployment completed successfully"